### ISSUE TITLE
Add new projects: sqlpp11 & sqlpp11_connector_sqlite3

### ISSUE THREAD

**Issue by theodelrieu** [mesonbuild/wrapweb#13]
Hi, I'd like to add those two projects in the wrap db, since it's the first time I do that, I do not have the rights do create new repos on that page (if I understood correctly)

Those projects have a dependency on Howard Hinnant's date library, which does not have archive releases, so I forked it, and added the `meson.build` there.

However, I removed every file except `date.h`, since the official repo contains several libraries, which is a bit confusing. Hence I'd like to know if I need to ask for a new `date` repo on this page too, and if not, what's the best way to proceed?

Thanks a lot!

**Comment by jpakkane** [comment]
For now we only keep actual releases in the wrapdb because we want to keep it stable. This ties in very poorly with projects that do not do releases. The simplest solution to your problem is to just have a git repo of your own with the necessary stuff and then write a wrap file to check it out with Git. This way you and everyone who wants to use your code can just check it out and Meson will download everything automatically (wrap deals with personal dependencies just fine, the use of wrapdb is optional).

**Comment by theodelrieu** [comment]
I'll do that, thanks!
