### ISSUE TITLE
New wrap: ArduinoCore-avr 1.6.20

### ISSUE THREAD

**Issue by tommie-lie** [mesonbuild/wrapweb#22]
Hi,

I took the idea from https://github.com/jpakkane/mesonarduino and spun it out further. I created `meson.build` definition for ArduinoCore-avr (https://github.com/arduino/ArduinoCore-avr), the core library of Arduino. Contrary to @jpakkane's repository, it provides the core library as a subproject and does not require the Arduino IDE to be installed. Also, it builds the core library as a static library and links it to the user's main project files.

I am, however, not sure if this is suitable as a wrap file available on the WrapDB:
1. It **requires** the use of cross files (using the avr-gcc toolchain and symbol definitions for different Arduino variants) that cannot easily be shipped via WrapDB.
2. The Arduino ecosystem consists of many very small additional libraries (most of them only one single C file). I also packaged one of the libraries that I plan to use and it is very straightforward to do so, but if done properly and people (other than me) are actually interested in doing Arduino development with meson, this could lead to a flood of new wrap projects.
3. Most users of the library will probably want to use a special template meson project to get the cross files and a wrapper script to avrdude required for some Arduino boards. So using it may not be as straightforward as other libraries for "regular" x86 development.

Please consider these arguments and decide if it's really useful to add those wraps to WrapDB. I will happily maintain the wraps that I regularly use separately and outside the WrapDB infrastructure if this is the more reasonable thing to do.

**Comment by jpakkane** [comment]
Providing libraries and sources for all project types was very much the intention of WrapDB, so having this in would be good. Since this is fairly new ground we can probably still get away with trying different approaches and removing those that don't work (if it happens).

The build definition should probably have an assert in it so it can only be used when cross compiling.

**Comment by tommie-lie** [comment]
I am also fine with removing stuff again if it turns out not to be useful -- let's see this as an experiment. :-) 

Of course the build definition contains the same assertion that your mesonarduino project contained to forbid non-cross builds. I'm already looking forward to your review!

**Comment by jpakkane** [comment]
One problem here is that wrapdb by design only contains point releases. We don't do Git head tracking. Based on ArduinoCore's repo they don't do releases at all (or at least they don't have any on their github page). This is going to need some sort of solution.

Nevertheless in the mean time we can create a git repo of our own with all the stuff and maybe I can write a blog post on using it (anyone else can do that too if they want, of course). Based on feedback we can then decide on how to go from there. Sounds reasonable?

**Comment by tommie-lie** [comment]
They do releases, just not in their git repository. Actually, I am not sure about the state of the ArduinoCore-avr repository. It seems to mirror the directory https://github.com/arduino/Arduino/commits/master/hardware/arduino/avr but it is not a git submodule, so I don't know how that works.

The official releases (with point version numbers) are available from http://downloads.arduino.cc/cores, the exact URLs can be found from the Arduino IDE: https://github.com/arduino/Arduino/blob/master/hardware/package_index_bundled.json#L20 (other versions are there as well, on a real installation the index can be found in `~/.arduino15/package_index.json`). I thought I'd use these URLs as canonical upstream sources in the wrap file.

**Comment by jpakkane** [comment]
That's cool. [Repository created](https://github.com/mesonbuild/arduinocore-avr/tree/1.6.20).
